spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/reserve_mysql?useSSL=true&allowPublicKeyRetrieval=true
    username: root
    password: password

  jpa:
    hibernate:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: update
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true

  # 스프링 시큐리티 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
