spring:
  jpa:
    hibernate:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
      ddl-auto: create
      show_sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
        use_sql_comments: true
  # 스프링 시큐리티 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration